eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8769

spring:
  application:
    name: service-zuul
  main:
    allow-bean-definition-overriding: true

#  /api-a/开头的url交给service-ribbon处理， /api-b/开头的url交给service-feign
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: eureka-client
    api-b:
      path: /api-b/**
      serviceId: service-feign

